spring.application.name=DataJpaWorkshop

#spring.datasource.url=jdbc:mysql://localhost:3306/SpringDataJPADB
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.jpa.properties.hibernate.format_sql=true


#H2 Configuration

spring.datasource.url=jdbc:h2:mem:ecomdb

spring.datasource.username=sa

spring.datasource.password=sa

spring.datasource.driver-class-name=org.h2.Driver

 

spring.h2.console.enabled=true

spring.h2.console.path=/h2-console